### PR TITLE
New person_single message for only one person in a room

### PR DESCRIPTION
**Pull request by nwithan8**

### CODE REVIEW

**Comment by Hexagon** [comment]
Thanks!

**Comment by whalehub** [comment]
@Hexagon Can you release a new version on NPM that includes this fix?

**Comment by whalehub** [comment]
@Hexagon Can you please release a new version on NPM that includes this fix?

**Comment by whalehub** [comment]
@Hexagon Can you please release a new version on https://www.npmjs.com/package/cryptalk that includes this fix?

**Pull request merged**
